#! /usr/bin/env bash

set -e

SCHEME="0.1.0"
VENDOR="Scribe security, Inc"
SHORT_DESC="Create SBOM for target"
LONG_DESC="Generate Software Bill Of Materials (SBOM) from container images and filesystems"
URL="https://github.com/scribe-security/bomber"
BASE_PATH=${HOME}/.scribe/bin/
CMD=gensbom

if [[ "$1" == "docker-cli-plugin-metadata" ]]; then
  cat << EOF
{
  "SchemaVersion": "${SCHEME}",
  "Vendor": "${VENDOR}",
  "URL": "${URL}",
  "ShortDescription": "${SHORT_DESC}"
}
EOF
  exit
fi

export PATH="${BASE_PATH}:$PATH"
if ! [ -x "$(command -v $CMD)" ]; then
  echo "${CMD} not found locally"
  exit 1
fi

$CMD bom "${@:2}"
